syntax = "proto3";
package accounts;
option go_package = ".;accounts";

import "accounts/definitions.proto";
import "accounts/accounts.proto";
import "accounts/wallet.proto";


service AccountService {
  rpc CreateWallet(CreateWalletRequest) returns (Wallet);
  rpc GetWallet(GetByIdRequest) returns (Wallet);
  rpc ListWallets(ListWalletsRequest) returns (ListWalletsResponse);
  rpc SetWalletPin(SetWalletPinRequest) returns (RemarksResponse);
  rpc ConfirmSetWalletPin(ConfirmSetWalletPinRequest) returns (RemarksResponse);
//  rpc CreditWallet(CreditWalletRequest) returns (CreditWalletResponse);


  rpc CreateStaticAccount(CreateStaticAccountRequest) returns (Account);
  rpc CreateVirtualAccount(CreateVirtualAccountRequest) returns (Account);
  rpc GetAccount(GetByIdRequest) returns (Account);
  rpc ListAccounts(ListAccountsRequest) returns (ListAccountsResponse);

  rpc StreamWalletUpdates(stream GetByIdRequest) returns (stream Wallet);
   rpc StreamWalletUpdatesFromServer(GetByIdRequest) returns (stream Wallet);
   rpc StreamWalletUpdatesFromClient(stream GetByIdRequest) returns (Wallet);
//  rpc CreditAccount(CreditAccountRequest) returns (CreditAccountResponse);
//  rpc DebitAccount(DebitAccountRequest) returns (DebitAccountResponse);
}



message Void {}