package src

import (
	"strings"
	"text/template"
)

// TemplateData holds all data needed for template execution
type TemplateData struct {
	PackageName string
	SourceFile  string
	Services    []*ServiceData
}

// ServiceData holds data for a single service
type ServiceData struct {
	Name        string
	Methods     []*MethodData
	ServiceName string
}

// MethodData holds data for a single method
type MethodData struct {
	Name              string
	ServiceName       string
	InputType         string
	OutputType        string
	InputTypeName     string
	OutputTypeName    string
	IsClientStreaming bool
	IsServerStreaming bool
	Topic             string
}

// Template helper functions
var templateFuncs = template.FuncMap{
	"lower": strings.ToLower,
	"title": strings.Title,
	"clientType": func(serviceName string) string {
		return strings.ToLower(serviceName[:1]) + serviceName[1:] + "Client"
	},
	"streamType": func(serviceName, methodName, side string) string {
		return serviceName + "_" + methodName + side
	},
	"streamImplType": func(serviceName, methodName, side string) string {
		streamType := serviceName + "_" + methodName + side
		return strings.ToLower(streamType[:1]) + streamType[1:]
	},
	"isUnary": func(m *MethodData) bool {
		return !m.IsClientStreaming && !m.IsServerStreaming
	},
	"isServerStreaming": func(m *MethodData) bool {
		return !m.IsClientStreaming && m.IsServerStreaming
	},
	"isClientStreaming": func(m *MethodData) bool {
		return m.IsClientStreaming && !m.IsServerStreaming
	},
	"isBidirectional": func(m *MethodData) bool {
		return m.IsClientStreaming && m.IsServerStreaming
	},
}

// Main template for the entire file
var FileTemplate = template.Must(template.New("file").Funcs(templateFuncs).Parse(`

// Code generated by protoc-gen-go-axon. DO NOT EDIT.
// source: {{.SourceFile}}

package {{.PackageName}}

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/nats-io/nats.go"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/encoding/protojson"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/trace"
)

// Tracing configuration
var (
	globalTracer     trace.Tracer
	globalPropagator propagation.TextMapPropagator
	tracingEnabled   bool
)

func EnableTracing() {
	tracingEnabled = true
	globalTracer = otel.Tracer("{{.PackageName}}")
	globalPropagator = otel.GetTextMapPropagator()
}

func DisableTracing() {
	tracingEnabled = false
	globalTracer = nil
	globalPropagator = nil
}

func IsTracingEnabled() bool {
	return tracingEnabled
}

type natsHeaderCarrier struct {
	header nats.Header
}

func (c natsHeaderCarrier) Get(key string) string {
	return c.header.Get(key)
}

func (c natsHeaderCarrier) Set(key string, value string) {
	c.header.Set(key, value)
}

func (c natsHeaderCarrier) Keys() []string {
	keys := make([]string, 0, len(c.header))
	for k := range c.header {
		keys = append(keys, k)
	}
	return keys
}

func startSpan(ctx context.Context, operationName string, kind trace.SpanKind, attrs ...attribute.KeyValue) (context.Context, trace.Span) {
	if !tracingEnabled || globalTracer == nil {
		return ctx, trace.SpanFromContext(ctx)
	}
	return globalTracer.Start(ctx, operationName, trace.WithSpanKind(kind), trace.WithAttributes(attrs...))
}

func injectTraceContext(ctx context.Context, header nats.Header) {
	if !tracingEnabled || globalPropagator == nil {
		return
	}
	globalPropagator.Inject(ctx, natsHeaderCarrier{header: header})
}

func extractTraceContext(ctx context.Context, header nats.Header) context.Context {
	if !tracingEnabled || globalPropagator == nil {
		return ctx
	}
	return globalPropagator.Extract(ctx, natsHeaderCarrier{header: header})
}

type CallOption func(*callOptions)

type callOptions struct {
	timeout time.Duration
	headers map[string]string
}

func defaultCallOptions() *callOptions {
	return &callOptions{
		timeout: 30 * time.Second,
		headers: make(map[string]string),
	}
}

func WithTimeout(d time.Duration) CallOption {
	return func(o *callOptions) {
		o.timeout = d
	}
}

func WithHeader(key, value string) CallOption {
	return func(o *callOptions) {
		o.headers[key] = value
	}
}



{{template "serviceRegistry" .}}

{{range .Services}}
{{template "serverInterface" .}}
{{template "clientInterface" .}}
{{template "clientImpl" .}}
{{template "serverRegistration" .}}
{{template "streamingInterfaces" .}}
{{template "playgroundSupport" .}}
{{end}}
`))

//#{{template "serverRegistration" .}}
